pipeline {
  agent any 
  stages{
    stage("build"){
      steps {
          echo "Building the application..."
      }
    }
    stage("Test"){
      steps{
         echo "test the application..."   
      }
    }
    stage("Deloy"){
      steps{
        echo "deplynge the application..."
      }
    }
  }
}
